config/routes.rb
Rails.application.routes.draw do
  get 'payments/index'
  resources :contacts, only: %i(new create index)

  mount RailsAdmin::Engine => '/admss', as: 'rails_admin'

  namespace :quizer, path: 'q' do
    resources :quizzes, except: :create, path: 'q', param: :owner_secret do
      collection do
        get :help
      end
      member do
        post :clone
        patch :toggle_active
      end

      resources :questions, except: :show do
        member do
          put :move_up
          put :move_down
          put :move_top
          put :move_bottom
        end

        resources :alternatives, except: :show
      end

      resources :results, only: %i(index show) do
        collection do
          get :logs
          delete :delete_all
        end
      end

      resources :exports, only: %i(index show)
      resources :payments, only: %i(index create) do
        collection do
          post :approve
        end
      end
    end

    resources :answers, path: 'a', only: %i(index new) do
      collection do
        post :upsert
        get :done
      end
    end
  end

  # Defines the root path route ("/")
  root "quizer/quizzes#index"
end

app/models/quizer.rb
module Quizer
  def self.table_name_prefix
    "quizer_"
  end
end

app/models/quizer/alternative.rb
class Quizer::Alternative < ApplicationRecord
  belongs_to :question, counter_cache: true

  has_many :answer_alternatives, class_name: 'Quizer::AnswerAlternative', dependent: :restrict_with_error
  has_many :answers, through: :answer_alternatives, class_name: 'Quizer::Answer'

  validates :description, presence: true

  DESCRIPTION_SURVEY_EXAMPLE = "Quality of the product/service".freeze

  DESCRIPTION_QUIZ_EXAMPLE = "Toronto".freeze

  def answers_count
    @answers_count ||= answers.count
  end

  def percentage
    if answers_count > 0 && question.answers_count > 0
      answers_count.to_f * 100 / question.answers_count.to_f
    else
      0
    end
  end
end

app/models/quizer/answer.rb
class Quizer::Answer < ApplicationRecord
  belongs_to :quiz, counter_cache: true
  belongs_to :question

  has_many :answer_alternatives, class_name: 'Quizer::AnswerAlternative', dependent: :destroy
  has_many :alternatives, through: :answer_alternatives, class_name: 'Quizer::Alternative'

  validates :session_hex, :quiz, :question, presence: true
  validates :descriptive, presence: true, if: :open_ended?

  validate :at_least_one_alternative

  scope :count_by_session, -> {
    count('DISTINCT session_hex')
  }

  private

  def open_ended?
    question&.open_ended?
  end

  def at_least_one_alternative
    if question && alternatives.blank?
      if question.select_one?
        errors.add :base, 'Select one alternative'
      elsif question.select_one_or_more?
        errors.add :base, 'Select one or more alternatives'
      end
    end
  end
end

app/models/quizer/answer_alternative.rb
class Quizer::AnswerAlternative < ApplicationRecord
  belongs_to :answer
  belongs_to :alternative
end

app/models/quizer/question.rb
class Quizer::Question < ApplicationRecord
  belongs_to :quiz, class_name: 'Quizer::Quiz'

  has_many :alternatives, class_name: 'Quizer::Alternative',
           dependent: :destroy

  has_many :answers, dependent: :destroy,
           class_name: 'Quizer::Answer',
           dependent: :destroy

  validates :description, :position, presence: true

  enum :question_type, %i(select_one select_one_or_more open_ended)

  DESCRIPTION_SURVEY_EXAMPLE = "Which of the following best describes your reason for using [product/service/company]?".freeze

  DESCRIPTION_QUIZ_EXAMPLE = "What is the capital city of Canada?".freeze

  QUESTION_TYPE_NAMES = {
    'select_one' => 'Select only one alternative',
    'select_one_or_more' => 'Select one or more alternatives',
    'open_ended' => 'Open ended, no alternatives'
  }.freeze

  def self.question_types_for_select(quiz)
    types = question_types.dup
    types.except!(:open_ended) if quiz.quiz?

    types.map do |key, value|
      [QUESTION_TYPE_NAMES[key], key]
    end
  end

  def answers_count
    @answers_count ||= answers.count
  end

  def prev_question
    quiz.questions.order(:position).where('position < ?', position).last
  end

  def next_question
    quiz.questions.order(:position).where('position > ?', position).first
  end

  def switch_position!(other_question)
    transaction do
      new_position = other_question.position
      other_question.update! position: position
      update! position: new_position
    end
  end

  def move_top!
    transaction do
      update! position: 0
      update_all_below!
    end
  end

  def move_bottom!
    transaction do
      update! position: quiz.questions.count - 1
      update_all_above!
    end
  end

  private

  def all_except_self
    quiz.questions.where('id != ?', id).order(:position)
  end

  def update_all_below!
    all_except_self.each.with_index do |q, i|
      q.update! position: i + 1
    end
  end

  def update_all_above!
    all_except_self.each.with_index do |q, i|
      q.update! position: i
    end
  end
end

app/controllers/quizer/alternatives_controller.rb
class Quizer::AlternativesController < Quizer::BaseController
  before_action :set_quiz_by_owner_secret, :set_question
  before_action :set_quizer_alternative, only: %i[ edit update destroy ]

  layout 'quiz'

  # GET /quizer/alternatives
  def index
    @alternatives = @question.alternatives
  end

  # GET /quizer/alternatives/new
  def new
    @alternative = @question.alternatives.new
  end

  # GET /quizer/alternatives/1/edit
  def edit
  end

  # POST /quizer/alternatives or /quizer/alternatives.json
  def create
    @alternative = @question.alternatives.new(alternative_params)

    if @alternative.save
      if params[:commit] == 'Save and go back'
        redirect_to quizer_quiz_question_alternatives_url(@quiz, @question)
      else
        redirect_to new_quizer_quiz_question_alternative_url(@quiz, @question)
      end
    else
      flash.now[:error] = @alternative.errors.full_messages.join('. ')
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /quizer/alternatives/1
  def update
    if @alternative.update(alternative_params)
      redirect_to quizer_quiz_question_alternatives_url(@quiz, @question)
    else
      flash.now[:error] = @alternative.errors.full_messages.join('. ')
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /quizer/alternatives/1
  def destroy
    @alternative.destroy

    redirect_to quizer_quiz_question_url(@quiz, @question)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = @quiz.questions.find_by(id: params[:question_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_quizer_alternative
      @alternative = @question.alternatives.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alternative_params
      params.require(:quizer_alternative).permit(:question_id, :description, :correct)
    end
end

app/controllers/quizer/answers_controller.rb
class Quizer::AnswersController < Quizer::BaseController
  before_action :set_quiz_by_audience_secret
  before_action :set_question, :set_session_hex, except: %i(index done)

  layout 'audience'

  def index
    @session_hex = SecureRandom.hex(10)
    @first_question = @quiz.questions.order(:position).first
  end

  def new
    @answer = @question.answers.find_or_initialize_by(session_hex: @session_hex)

    if !@question.open_ended? && @question.alternatives.blank?
      flash.now[:error] = "This question has no alternatives"
    end
  end

  def upsert
    @answer = @question.answers.find_or_initialize_by(session_hex: @session_hex)
    @answer.quiz = @quiz
    @answer.assign_attributes(answer_params)

    if @answer.save
      redirect_to_next_question
    else
      flash.now[:error] = @answer.errors.full_messages.join('. ')
      render action: :new, status: :unprocessable_entity
    end
  end

  def done
    if @quiz.quiz?
      @answers_count = @quiz.questions.count
      @correct_answers_count = @quiz.correct_answers_count(params[:session_hex])
    end
  end

  private

  def redirect_to_next_question
    session_hex = answer_params[:session_hex]

    if @question.next_question
      redirect_to new_quizer_answer_path(
        s: params[:s],
        session_hex: session_hex,
        question_id: @question.next_question.id
      )
    else
      redirect_to done_quizer_answers_path(s: params[:s], session_hex: session_hex)
    end
  end

  def set_question
    @question = Quizer::Question.find(params[:question_id])
  end

  def set_session_hex
    @session_hex = params[:session_hex] || answer_params[:session_hex]
  end

  # Only allow a list of trusted parameters through.
  def answer_params
    params.require(:quizer_answer).permit(
      :quiz_id, :session_hex, :descriptive,
      # checkboxes send IDs as array, radio single option as string
      :alternative_ids, alternative_ids: []
    )
  end
end

app/controllers/quizer/base_controller.rb
class Quizer::BaseController < ApplicationController

  protected

  def set_quiz_by_owner_secret
    @quiz = Quizer::Quiz.find_by!(owner_secret: params[:owner_secret] || params[:quiz_owner_secret])
  end

  def set_quiz_by_audience_secret
    @quiz = Quizer::Quiz.find_by!(audience_secret: params[:s])
  end
end

app/controllers/quizer/exports_controller.rb
class Quizer::ExportsController < Quizer::BaseController
  before_action :set_quiz_by_owner_secret

  layout 'quiz'

  def index
  end

  def show
    response.headers['Content-Type'] = 'text/csv'

    if params[:id] == 'questions'
      send_data QuizerExporter.new(@quiz).questions_csv, filename: "questions.csv"
    elsif params[:id] == 'answers'
      send_data QuizerExporter.new(@quiz).answers_csv, filename: "answers.csv"
    end
  end
end

app/controllers/quizer/questions_controller.rb
class Quizer::QuestionsController < Quizer::BaseController
  before_action :set_quiz_by_owner_secret
  before_action :set_question, only: %i[ edit update destroy move_up move_down move_top move_bottom ]

  layout 'quiz'

  # GET /quizer/questions
  def index
    @questions = @quiz.questions.order(:position)
  end

  # GET /quizer/questions/new
  def new
    @question = @quiz.questions.new
  end

  # GET /quizer/questions/1/edit
  def edit
  end

  # POST /quizer/questions
  def create
    @question = @quiz.questions.new(question_params)
    @question.position = @quiz.questions.maximum(:position).to_i + 1

    if @question.save
      if @question.open_ended?
        redirect_to quizer_quiz_questions_url(@quiz)
      else
        redirect_to quizer_quiz_question_alternatives_url(@quiz, @question)
      end
    else
      flash.now[:error] = @question.errors.full_messages.join('. ')
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /quizer/questions/1
  def update
    if @question.update(question_params)
      if params[:go_back]
        redirect_to params[:go_back]
      else
        redirect_to quizer_quiz_questions_url(@quiz)
      end
    else
      flash.now[:error] = @question.errors.full_messages.join('. ')
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /quizer/questions/1
  def destroy
    @question.destroy

    redirect_to quizer_quiz_questions_url(@quiz)
  end

  def move_up
    @question.switch_position!(@question.prev_question)
    redirect_to quizer_quiz_questions_url(@quiz)
  end

  def move_down
    @question.switch_position!(@question.next_question)
    redirect_to quizer_quiz_questions_url(@quiz)
  end

  def move_top
    @question.move_top!
    redirect_to quizer_quiz_questions_url(@quiz)
  end

  def move_bottom
    @question.move_bottom!
    redirect_to quizer_quiz_questions_url(@quiz)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = @quiz.questions.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:quizer_question).permit(:quiz_id, :question_type, :description)
    end
end

app/controllers/quizer/quizzes_controller.rb
class Quizer::QuizzesController < Quizer::BaseController
  before_action :set_quiz_by_owner_secret, only: %i(show results edit destroy update clone toggle_active)

  layout :resolve_layout

  # GET /quizer/quizzes
  def index
  end

  def help
  end

  # GET /quizer/quizzes/1
  def show
    @last_answer = @quiz.answers.last
  end

  # GET /quizer/quizzes/new
  def new
    description = if params[:quiz_type] == 'quiz'
      Quizer::Quiz::DESCRIPTION_QUIZ_EXAMPLE
    else
      Quizer::Quiz::DESCRIPTION_SURVEY_EXAMPLE
    end

    @quiz = Quizer::Quiz.new(
      quiz_type: params[:quiz_type],
      description: description
    )
    @quiz.generate_secrets
    @quiz.save!

    redirect_to @quiz
  end

  # GET /quizer/quizzes/1/edit
  def edit
  end

  # PATCH/PUT /quizer/quizzes/1
  def update
    if @quiz.update(quiz_params)
      redirect_to quizer_quiz_url(@quiz)
    else
      flash[:error] = @quiz.errors.full_messages.join('. ')
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /quizer/quizzes/1
  def destroy
    @quiz.destroy

    redirect_to quizer_quizzes_url
  end

  def toggle_active
    @quiz.update active: !@quiz.active

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("#{@quiz.id}-active", partial: 'active')
      }
      format.html { redirect_to @quiz }
    end
  end

  def clone
    cloned = @quiz.dup
    cloned.generate_secrets
    cloned.save!

    @quiz.questions.includes(:alternatives).find_each do |question|
      cloned_question = question.dup
      cloned_question.quiz = cloned
      cloned_question.save!

      question.alternatives.find_each do |alternative|
        cloned_question.alternatives << alternative.dup
      end
    end

    redirect_to cloned
  end

  private

  def resolve_layout
    case action_name
    when 'index'
      'audience'
    else
      'quiz'
    end
  end

  # Only allow a list of trusted parameters through.
  def quiz_params
    params.require(:quizer_quiz).permit(:description, :public_results, :quiz_type)
  end
end

app/controllers/quizer/results_controller.rb
class Quizer::ResultsController < Quizer::BaseController
  before_action :set_quiz_by_owner_secret
  before_action :no_answer_warning, only: %i(index logs)

  layout 'quiz'

  def index
    @total_people = @quiz.answers.count_by_session
    @total_questions = @quiz.questions.count
  end

  def show
    @question = @quiz.questions.find(params[:id])
    @alternatives = @question.alternatives.includes(:answers)
  end

  def logs
    @answers = @quiz.answers.
      includes(:alternatives, :quiz, :question).
      order(created_at: :desc).
      paginate(page: params[:page], per_page: 30)
  end

  def delete_all
    @quiz.answers.destroy_all

    redirect_to quizer_quiz_results_path(@quiz)
  end

  private

  def no_answer_warning
    if @quiz.answers.blank?
      flash[:error] = "Nobody has answered your #{@quiz.quiz_type} so far"
    end
  end
end

app/views/quizer/answers/_descriptive.html.slim
  = f.text_area :descriptive, class: 'form-control', rows: 4, value: answer.descriptive

app/views/quizer/answers/_open_ended.html.slim
  = f.text_area :descriptive, class: 'form-control', rows: 4, value: answer.descriptive

app/views/quizer/answers/_select_one.html.slim
- question.alternatives.each.with_index do |alternative, i|
  .form-check.m-2
    = f.radio_button :alternative_ids, alternative.id, class: 'form-check-input',
      checked: answer.alternatives.include?(alternative)
    label.form-check-label for="quizer_answer_alternative_ids_#{alternative.id}"
      strong.me-2 =  i + 1
      span = alternative.description

app/views/quizer/answers/_select_one_or_more.html.slim
- question.alternatives.each.with_index do |alternative, i|
  .form-check.m-2
    = f.check_box :alternative_ids,
      { multiple: true, class: 'form-check-input', checked: answer.alternatives.include?(alternative) },
      alternative.id, nil
    label.form-check-label for="quizer_answer_alternative_ids_#{alternative.id}"
     strong.me-3 =  i + 1
     span = alternative.description

app/views/quizer/answers/done.html.slim
- if @quiz.quiz?
  h4.pb-2
    | Thank you for playing the quiz!
    i.bi.bi-rocket-takeoff.ms-2

  p.lead  You answered correctly #{@correct_answers_count} of #{@answers_count} questions.

- else
  h4.pb-2
    | Thank you for completing our survey!
    i.bi.bi-rocket-takeoff.ms-2

  p.lead.pt-4
    | We appreciate your time and effort in providing us with your valuable feedback. Your responses will help us improve our services and better understand the needs of our audience.
  p.lead.pb-4
    | If you know anyone else who might be interested in sharing their thoughts and opinions, please feel free to share this survey with them using the link below. Your referrals are greatly appreciated!

  .d-flex.justify-content-center
    .input-group.mt-4.share-link
      = text_field_tag 'audience-link', quizer_answers_url(s: @quiz.audience_secret,
        only_path: false), readonly: true, class: 'form-control'
      span.input-group-text
        = link_to '#', class: 'clipboard', data: { clipboard_target: '#audience-link' } do
          i.bi.bi-clipboard

app/views/quizer/answers/index.html.slim
- if !@quiz.active
  .alert.alert-warning
    | This survey was deactivated by the owner
- elsif !@first_question
  .alert.alert-warning
    | This survey has no questions
- else
  p.lead.multiline
    = @quiz.description

  = link_to new_quizer_answer_path(s: @quiz.audience_secret, question_id: @first_question.id, session_hex: @session_hex),
    class: 'btn btn-lg btn-primary' do
    i.bi.bi-collection-play-fill.me-2
    | Start Survey

app/views/quizer/answers/new.html.slim
= form_with(model: Quizer::Answer.new, url: upsert_quizer_answers_path(s: @quiz.audience_secret, question_id: @question.id)) do |f|
  = f.hidden_field :session_hex, value: @session_hex
  hr.line

  h4 = @question.description

  .text-start.p-4
    = render partial: @question.question_type, locals: { f: f, question: @question, answer: @answer }

  .my-2
    button.btn.btn-primary.btn-lg type="submit"
      i.bi.bi-send-fill.me-2
      | Send

  hr.line
  .btn-group
    - if @question.prev_question
      = link_to new_quizer_answer_path(s: @quiz.audience_secret, question_id: @question.prev_question.id, session_hex: @session_hex),
        class: 'btn btn-secondary btn-sm' do
        i.bi.bi-skip-backward-fill.me-2
        | Previous question
    - if @question.next_question
      = link_to new_quizer_answer_path(s: @quiz.audience_secret, question_id: @question.next_question.id, session_hex: @session_hex),
        class: 'btn btn-secondary btn-sm' do
        i.bi.bi-skip-forward-fill.me-2
        | Skip question
    - else
      = link_to 'Skip question', done_quizer_answers_path(s: @quiz.audience_secret),
        class: 'btn btn-secondary btn-sm'