config/routes.rb
Rails.application.routes.draw do
  get 'payments/index'
  resources :contacts, only: %i(new create index)

  mount RailsAdmin::Engine => '/admss', as: 'rails_admin'

  namespace :quizer, path: 'q' do
    resources :quizzes, except: :create, path: 'q', param: :owner_secret do
      collection do
        get :help
      end
      member do
        post :clone
        patch :toggle_active
      end

      resources :questions, except: :show do
        member do
          put :move_up
          put :move_down
          put :move_top
          put :move_bottom
        end

        resources :alternatives, except: :show
      end

      resources :results, only: %i(index show) do
        collection do
          get :logs
          delete :delete_all
        end
      end

      resources :exports, only: %i(index show)
      resources :payments, only: %i(index create) do
        collection do
          post :approve
        end
      end
    end

    resources :answers, path: 'a', only: %i(index new) do
      collection do
        post :upsert
        get :done
      end
    end
  end

  # Defines the root path route ("/")
  root "quizer/quizzes#index"
end

app/views/layouts/_alerts.html.slim
- if notice
  .alert.alert-success.alert-dismissible.fade.show.my-2 role="alert"
    = notice
    button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
- if error
  .alert.alert-warning.alert-dismissible.fade.show.my-2 role="alert"
    = error
    button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"

app/views/layouts/_head.html.slim
head
  title
    | Cookies Free - Survey Maker
  meta[name="viewport" content="width=device-width,initial-scale=1"]
  meta name="author" content="Tiago Geraldi"
  meta name="description" content="Easily create and customize your own surveys or quizzes with our free user-friendly tool. No sign-up required. No sessions or cookies. We don't collect or store any private data. No coding or technical knowledge required!"
  meta name="description" content="survey maker, quiz maker, online surveys, online quizzes, free, no-signup, no registration, no tracking, no credit card, no cookies, no sessions, no private data, GDPR friendly"
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags

  link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2220%22 fill=%22%23724d3f%22></rect><path fill=%22%23fff%22 d=%22M47.75 28.67L47.75 28.67Q47.75 29.93 46.99 30.83Q46.22 31.73 45.23 32.18L45.23 32.18Q42.89 30.56 39.74 29.12Q36.59 27.68 31.55 27.68L31.55 27.68Q27.41 27.68 23.90 29.12Q20.39 30.56 17.78 33.35Q15.17 36.14 13.69 40.37Q12.20 44.60 12.20 50.09L12.20 50.09Q12.20 55.67 13.64 59.81Q15.08 63.95 17.65 66.74Q20.21 69.53 23.81 70.92Q27.41 72.32 31.82 72.32L31.82 72.32Q36.50 72.32 39.97 71.02Q43.43 69.71 45.77 67.91L45.77 67.91Q46.67 68.27 47.48 69.22Q48.29 70.16 48.29 71.42L48.29 71.42Q48.29 73.31 46.13 74.84L46.13 74.84Q44.06 76.28 40.46 77.41Q36.86 78.53 31.28 78.53L31.28 78.53Q25.61 78.53 20.75 76.73Q15.89 74.93 12.34 71.38Q8.78 67.82 6.71 62.51Q4.64 57.20 4.64 50.09L4.64 50.09Q4.64 42.98 6.76 37.63Q8.87 32.27 12.47 28.67Q16.07 25.07 20.89 23.27Q25.70 21.47 31.01 21.47L31.01 21.47Q34.70 21.47 37.81 22.10Q40.91 22.73 43.12 23.77Q45.32 24.80 46.54 26.11Q47.75 27.41 47.75 28.67ZM64.67 22.64L94.55 22.64Q94.82 23.09 95.09 23.86Q95.36 24.62 95.36 25.52L95.36 25.52Q95.36 27.05 94.64 27.95Q93.92 28.85 92.57 28.85L92.57 28.85L68.09 28.85L68.09 47.57L91.40 47.57Q91.67 48.02 91.94 48.78Q92.21 49.55 92.21 50.45L92.21 50.45Q92.21 51.98 91.49 52.88Q90.77 53.78 89.42 53.78L89.42 53.78L68.09 53.78L68.09 77.27Q67.64 77.45 66.70 77.63Q65.75 77.81 64.76 77.81L64.76 77.81Q60.71 77.81 60.71 74.57L60.71 74.57L60.71 26.60Q60.71 24.80 61.79 23.72Q62.87 22.64 64.67 22.64L64.67 22.64Z%22></path></svg>"

app/views/layouts/audience.html.slim
doctype html
html
  = render '/layouts/head'

  body style="height: 100%"
    .container.d-flex.justify-content-center.flex-column.text-center
      = render '/layouts/alerts'
      .content.mb-5.pb-4.mt-2
        = yield
      footer.mt-2.pt-4
        = link_to '/', class: 'link-secondary link-sm text-decoration-none', target: '_blank' do
          = image_tag 'cookies-free.png',
            alt: 'Cookies Free', width: 80
          .fs-6.text-muted.lh-1.fw-lighter.mt-1
            | Surveys and quizzes
            br
            | without cookies or sessions for free

app/views/layouts/quiz.html.slim
doctype html
html
  = render '/layouts/head'

  body
    nav.navbar.navbar-expand.bg-light
      .container-sm
        a.navbar-brand[href="/"]
          = image_tag 'cookies-free.png', alt: 'Cookies Free', width: 70
        button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
        #navbarSupportedContent.collapse.navbar-collapse
          ul.navbar-nav.me-auto.mb-2.mb-lg-0
            li.nav-item
              = link_to "#{@quiz&.quiz_type&.humanize || 'Survey'} Maker", quizer_quizzes_url, class: 'nav-link'
            li.nav-item
              = link_to "Help", help_quizer_quizzes_url, class: 'nav-link'
            li.nav-item
              = link_to 'Contact us', new_contact_url, class: 'nav-link'
    .container-sm
      - if @quiz&.persisted?
        .mt-3
          nav.navbar.navbar-primary.bg-dark.bg-opacity-10.rounded.navbar-expand-lg
            .container-fluid
              button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#quiz-actions" aria-controls="quiz-actions" aria-expanded="false" aria-label="Toggle navigation"
                span class="navbar-toggler-icon"

              #quiz-actions.collapse.navbar-collapse
                ul.navbar-nav
                  li.nav-link = link_to @quiz, class: 'btn btn-sm' do
                    i.bi.bi-house.me-1
                    | Home

                  - if @quiz.questions.count == 0
                    li.nav-link = link_to new_quizer_quiz_question_path(@quiz), class: 'btn btn-sm' do
                      i.bi.bi-question-diamond.me-1
                      | New question
                  - else
                    li.nav-link = link_to quizer_quiz_questions_url(@quiz), class: 'btn btn-sm' do
                      i.bi.bi-question-diamond.me-1
                      | Questions
                      span.badge.text-bg-light.ms-1 = @quiz.questions.count

                  li.nav-link = link_to edit_quizer_quiz_path(@quiz), class: 'btn btn-sm' do
                    i.bi.bi-pencil.me-1
                    | Edit #{@quiz.quiz_type.humanize}

                  li.nav-link = link_to quizer_quiz_results_path(@quiz), class: 'btn btn-sm' do
                    i.bi.bi-bullseye.me-1
                    | Results / Answers
                    span.badge.text-bg-light.ms-1 = @quiz.answers_count

                  li.nav-link = link_to quizer_quiz_exports_path(@quiz), class: 'btn btn-sm' do
                    i.bi.bi-arrow-bar-down.me-1
                    | Export data

                  li.nav-link = button_to clone_quizer_quiz_path(@quiz),
                    class: 'btn btn-sm',
                    method: :post,
                    data: { turbo_confirm: "This action is going to create a new #{@quiz.quiz_type} cloning your current questions and alternatives. Do you want to continue?" } do
                    i.bi.bi-back.me-1
                    | Clone #{@quiz.quiz_type.humanize}

      = render '/layouts/alerts'

      .mt-4 = yield

app/views/layouts/welcome.html.slim
doctype html
html
  = render '/layouts/head'
  body
    main
      .px-4.py-5.my-5.text-center
        = image_tag 'cookies-free.png', alt: 'Cookies Free', width: 150, class: 'd-block mx-auto mb-4'

        h1.display-5.fw-bold
          | Survey Maker

        .col-lg-6.mx-auto
          = yield